packages:
  - fixtures/*

catalogMode: strict

catalogs:
  dev:
    '@angular/core': ^20.3.2
    '@arethetypeswrong/cli': ^0.18.2
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^20.0.0
    '@commitlint/cz-commitlint': ^19.8.1
    '@commitlint/format': ^20.0.0
    '@commitlint/lint': ^20.0.0
    '@commitlint/load': ^19.8.1
    '@ngrx/effects': ^20.0.1
    '@ngrx/operators': ^20.0.1
    '@ngrx/signals': ^20.0.1
    '@ngrx/store': ^20.0.1
    '@testing-library/angular': ^18.0.0
    '@testing-library/jest-dom': ^6.8.0
    '@types/fs-extra': ^11.0.4
    '@types/node': ^22.18.6
    '@vitest/coverage-v8': ^3.2.4
    bumpp: ^10.2.3
    changelogithub: ^13.16.0
    commitizen: ^4.3.1
    eslint-typegen: ^2.3.0
    execa: ^9.6.0
    fast-glob: ^3.3.3
    fs-extra: ^11.3.2
    is-ci: ^4.1.0
    jiti: ^2.6.0
    nano-staged: ^0.8.0
    simple-git-hooks: ^2.13.1
    tailwindcss: ^4.1.13
    tsdown: ^0.14.2
    tsx: ^4.20.6
    typescript: ~5.8.3
    unbuild: ^3.6.0
    vitest: ^3.2.4
  peer:
    '@prettier/plugin-xml': ^3.4.2
    eslint: ^9.36.0
    eslint-plugin-better-tailwindcss: ^3.7.9
    eslint-plugin-erasable-syntax-only: ^0.3.1
    eslint-plugin-format: ^1.0.2
    prettier-plugin-slidev: ^1.0.5
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/js': ^9.36.0
    '@eslint/markdown': ^7.3.0
    '@ngrx/eslint-plugin': ^20.0.1
    '@stylistic/eslint-plugin': ^5.4.0
    '@typescript-eslint/eslint-plugin': ^8.44.1
    '@typescript-eslint/parser': ^8.44.1
    '@typescript-eslint/utils': ^8.44.1
    '@vitest/eslint-plugin': ^1.3.13
    angular-eslint: ^20.3.0
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.4
    eslint-merge-processors: ^2.0.0
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-jest-dom: ^5.5.0
    eslint-plugin-jsdoc: ^54.7.0
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-n: ^17.23.1
    eslint-plugin-perfectionist: ^4.15.0
    eslint-plugin-pnpm: ^1.1.2
    eslint-plugin-prefer-arrow-functions: ^3.8.1
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-testing-library: ^7.10.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^60.0.0
    eslint-plugin-unused-imports: ^4.2.0
    eslint-plugin-yml: ^1.18.0
    globals: ^16.4.0
    jsonc-eslint-parser: ^2.4.1
    local-pkg: ^1.1.2
    toml-eslint-parser: ^0.10.0
    typescript-eslint: ^8.44.1
    yaml-eslint-parser: ^1.3.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@fabdeh/*'

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
