packages:
  - fixtures/*

catalogMode: strict

catalogs:
  dev:
    '@angular/core': ^21.2.5
    '@arethetypeswrong/cli': ^0.18.2
    '@commitlint/cli': ^20.5.0
    '@commitlint/config-conventional': ^20.5.0
    '@commitlint/cz-commitlint': ^20.5.0
    '@commitlint/format': ^20.1.0
    '@commitlint/lint': ^20.5.0
    '@commitlint/load': ^20.5.0
    '@ngrx/effects': ^21.0.1
    '@ngrx/operators': ^21.0.1
    '@ngrx/signals': ^21.0.1
    '@ngrx/store': ^21.0.1
    '@testing-library/angular': ^19.2.1
    '@testing-library/jest-dom': ^6.9.1
    '@types/fs-extra': ^11.0.4
    '@types/node': ^24.12.0
    '@vitest/coverage-v8': ^4.1.0
    bumpp: ^11.0.1
    changelogithub: ^14.0.0
    commitizen: ^4.3.1
    eslint-typegen: ^2.3.1
    execa: ^9.6.1
    fast-glob: ^3.3.3
    fs-extra: ^11.3.4
    is-ci: ^4.1.0
    jiti: ^2.6.1
    nano-staged: ^0.9.0
    semver: ^7.7.4
    simple-git-hooks: ^2.13.1
    tailwindcss: ^4.2.2
    tsdown: ^0.21.4
    tsx: ^4.21.0
    typescript: ^5.9.3
    unbuild: ^3.6.0
    vitest: ^4.1.0
  peer:
    '@prettier/plugin-xml': ^3.4.2
    eslint: ^9.39.4
    eslint-plugin-better-tailwindcss: ^4.3.2
    eslint-plugin-erasable-syntax-only: ^0.4.0
    eslint-plugin-format: ^1.5.0
    prettier-plugin-slidev: ^1.0.5
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^1.1.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.7.1
    '@eslint/js': ^9.39.4
    '@eslint/markdown': ^7.5.1
    '@ngrx/eslint-plugin': ^21.0.1
    '@stylistic/eslint-plugin': ^5.10.0
    '@typescript-eslint/eslint-plugin': ^8.57.1
    '@typescript-eslint/parser': ^8.57.1
    '@typescript-eslint/utils': ^8.57.1
    '@vitest/eslint-plugin': ^1.6.12
    angular-eslint: ^21.3.1
    eslint-config-flat-gitignore: ^2.2.1
    eslint-flat-config-utils: ^3.0.2
    eslint-merge-processors: ^2.0.0
    eslint-plugin-import-x: ^4.16.2
    eslint-plugin-jest-dom: ^5.5.0
    eslint-plugin-jsdoc: ^62.8.0
    eslint-plugin-jsonc: ^2.21.1
    eslint-plugin-n: ^17.24.0
    eslint-plugin-perfectionist: ^5.7.0
    eslint-plugin-pnpm: ^1.6.0
    eslint-plugin-prefer-arrow-functions: ^3.9.1
    eslint-plugin-regexp: ^3.1.0
    eslint-plugin-testing-library: ^7.16.0
    eslint-plugin-toml: ^1.3.1
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-unused-imports: ^4.4.1
    eslint-plugin-yml: ^3.3.1
    globals: ^17.4.0
    jsonc-eslint-parser: ^2.4.2
    local-pkg: ^1.1.2
    typescript-eslint: ^8.57.1
    yaml-eslint-parser: ^2.0.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@fabdeh/*'
  - '@isaacs/brace-expansion'

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
