[
  "<ignored>",
  "<ignored>",
  "<ignored>",
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/javascript/rules",
    "plugins": [
      "@typescript-eslint",
      "prefer-arrow-functions",
      "unused-imports",
    ],
    "rules": [
      "accessor-pairs",
      "array-callback-return",
      "block-scoped-var",
      "constructor-super",
      "default-case-last",
      "dot-notation",
      "eqeqeq",
      "for-direction",
      "getter-return",
      "id-denylist",
      "new-cap",
      "no-alert",
      "no-async-promise-executor",
      "no-caller",
      "no-case-declarations",
      "no-class-assign",
      "no-cond-assign",
      "no-compare-neg-zero",
      "no-console",
      "no-const-assign",
      "no-constant-binary-expression",
      "no-constant-condition",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-else-if",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-empty-static-block",
      "no-eval",
      "no-ex-assign",
      "no-extend-native",
      "no-extra-bind",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-import-assign",
      "no-implied-eval",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-iterator",
      "no-labels",
      "no-lone-blocks",
      "no-lonely-if",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-multi-str",
      "no-new",
      "no-new-func",
      "no-new-native-nonconstructor",
      "no-new-wrappers",
      "no-nonoctal-decimal-escape",
      "no-obj-calls",
      "no-octal",
      "no-octal-escape",
      "no-plusplus",
      "no-prototype-builtins",
      "no-proto",
      "no-redeclare",
      "no-regex-spaces",
      "no-restricted-globals",
      "no-restricted-properties",
      "no-restricted-syntax",
      "no-self-assign",
      "no-self-compare",
      "no-sequences",
      "no-setter-return",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-template-curly-in-string",
      "no-this-before-super",
      "no-throw-literal",
      "no-undef",
      "no-undef-init",
      "no-unassigned-vars",
      "no-unexpected-multiline",
      "no-unmodified-loop-condition",
      "no-unneeded-ternary",
      "no-unreachable",
      "no-unreachable-loop",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unsafe-optional-chaining",
      "no-unused-expressions",
      "no-unused-labels",
      "no-unused-private-class-members",
      "- no-unused-vars",
      "no-use-before-define",
      "no-useless-assignment",
      "no-useless-backreference",
      "no-useless-call",
      "no-useless-catch",
      "no-useless-computed-key",
      "no-useless-constructor",
      "no-useless-escape",
      "no-useless-rename",
      "no-useless-return",
      "no-var",
      "no-with",
      "object-shorthand",
      "prefer-arrow-callback",
      "prefer-arrow-functions/prefer-arrow-functions",
      "prefer-const",
      "prefer-exponentiation-operator",
      "prefer-object-spread",
      "prefer-promise-reject-errors",
      "prefer-regex-literals",
      "prefer-rest-params",
      "prefer-spread",
      "prefer-template",
      "preserve-caught-error",
      "require-yield",
      "symbol-description",
      "unicode-bom",
      "use-isnan",
      "unused-imports/no-unused-imports",
      "unused-imports/no-unused-vars",
      "valid-typeof",
      "vars-on-top",
      "yoda",
      "@typescript-eslint/ban-ts-comment",
      "@typescript-eslint/no-extra-non-null-assertion",
      "@typescript-eslint/no-misused-new",
      "@typescript-eslint/no-non-null-asserted-optional-chain",
      "@typescript-eslint/no-require-imports",
      "@typescript-eslint/no-this-alias",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/comments/rules",
    "plugins": [
      "@eslint-community/eslint-comments",
    ],
    "rules": [
      "@eslint-community/eslint-comments/disable-enable-pair",
      "@eslint-community/eslint-comments/no-aggregating-enable",
      "@eslint-community/eslint-comments/no-duplicate-disable",
      "@eslint-community/eslint-comments/no-unlimited-disable",
      "@eslint-community/eslint-comments/no-unused-disable",
      "@eslint-community/eslint-comments/no-unused-enable",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/node/rules",
    "plugins": [
      "n",
    ],
    "rules": [
      "n/handle-callback-err",
      "n/no-callback-literal",
      "n/no-deprecated-api",
      "n/no-exports-assign",
      "n/no-new-require",
      "n/no-path-concat",
      "n/prefer-global/buffer",
      "n/prefer-global/process",
      "n/prefer-promises/dns",
      "n/prefer-promises/fs",
      "n/process-exit-as-throw",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/imports/rules",
    "plugins": [
      "import-x",
    ],
    "rules": [
      "import-x/consistent-type-specifier-style",
      "import-x/default",
      "import-x/export",
      "import-x/first",
      "import-x/named",
      "import-x/no-absolute-path",
      "import-x/no-deprecated",
      "import-x/no-duplicates",
      "import-x/no-empty-named-blocks",
      "import-x/no-extraneous-dependencies",
      "import-x/no-mutable-exports",
      "import-x/no-named-as-default",
      "import-x/no-named-as-default-member",
      "import-x/no-named-default",
      "import-x/no-self-import",
      "import-x/no-useless-path-segments",
      "import-x/no-webpack-loader-syntax",
      "import-x/newline-after-import",
    ],
  },
  {
    "files": [
      "**/*.?([cm])ts?(x)",
    ],
    "name": "fabdeh/imports/ts-disables",
    "rules": [
      "- import-x/named",
      "- import-x/no-deprecated",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/perfectionist/rules",
    "plugins": [
      "perfectionist",
    ],
    "rules": [
      "perfectionist/sort-exports",
      "perfectionist/sort-imports",
      "perfectionist/sort-intersection-types",
      "perfectionist/sort-named-exports",
      "perfectionist/sort-named-imports",
      "perfectionist/sort-switch-case",
      "perfectionist/sort-union-types",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/unicorn/rules",
    "plugins": [
      "unicorn",
    ],
    "rules": [
      "unicorn/catch-error-name",
      "unicorn/consistent-date-clone",
      "unicorn/consistent-empty-array-spread",
      "unicorn/consistent-existence-index-check",
      "unicorn/consistent-function-scoping",
      "unicorn/custom-error-definition",
      "unicorn/error-message",
      "unicorn/escape-case",
      "unicorn/explicit-length-check",
      "unicorn/filename-case",
      "unicorn/new-for-builtins",
      "unicorn/no-abusive-eslint-disable",
      "unicorn/no-anonymous-default-export",
      "unicorn/no-array-for-each",
      "unicorn/no-array-method-this-argument",
      "unicorn/no-array-reduce",
      "unicorn/no-await-expression-member",
      "unicorn/no-await-in-promise-methods",
      "unicorn/no-document-cookie",
      "unicorn/no-empty-file",
      "unicorn/no-for-loop",
      "unicorn/no-hex-escape",
      "unicorn/no-instanceof-builtins",
      "unicorn/no-invalid-fetch-options",
      "unicorn/no-invalid-remove-event-listener",
      "unicorn/no-lonely-if",
      "unicorn/no-magic-array-flat-depth",
      "unicorn/no-negated-condition",
      "unicorn/no-negation-in-equality-check",
      "unicorn/no-new-array",
      "unicorn/no-new-buffer",
      "unicorn/no-null",
      "unicorn/no-process-exit",
      "unicorn/no-single-promise-in-promise-methods",
      "unicorn/no-thenable",
      "unicorn/no-this-assignment",
      "unicorn/no-typeof-undefined",
      "unicorn/no-unnecessary-await",
      "unicorn/no-unnecessary-array-flat-depth",
      "unicorn/no-unnecessary-array-splice-count",
      "unicorn/no-unnecessary-slice-end",
      "unicorn/no-unused-properties",
      "unicorn/no-useless-fallback-in-spread",
      "unicorn/no-useless-length-check",
      "unicorn/no-useless-promise-resolve-reject",
      "unicorn/no-useless-spread",
      "unicorn/no-useless-switch-case",
      "unicorn/no-zero-fractions",
      "unicorn/number-literal-case",
      "unicorn/numeric-separators-style",
      "unicorn/prefer-array-find",
      "unicorn/prefer-array-flat",
      "unicorn/prefer-array-flat-map",
      "unicorn/prefer-array-index-of",
      "unicorn/prefer-array-some",
      "unicorn/prefer-at",
      "unicorn/prefer-blob-reading-methods",
      "unicorn/prefer-code-point",
      "unicorn/prefer-date-now",
      "unicorn/prefer-default-parameters",
      "unicorn/prefer-export-from",
      "unicorn/prefer-import-meta-properties",
      "unicorn/prefer-includes",
      "unicorn/prefer-keyboard-event-key",
      "unicorn/prefer-logical-operator-over-ternary",
      "unicorn/prefer-math-min-max",
      "unicorn/prefer-math-trunc",
      "unicorn/prefer-modern-math-apis",
      "unicorn/prefer-negative-index",
      "unicorn/prefer-node-protocol",
      "unicorn/prefer-number-properties",
      "unicorn/prefer-object-from-entries",
      "unicorn/prefer-optional-catch-binding",
      "unicorn/prefer-query-selector",
      "unicorn/prefer-regexp-test",
      "unicorn/prefer-set-has",
      "unicorn/prefer-set-size",
      "unicorn/prefer-single-call",
      "unicorn/prefer-spread",
      "unicorn/prefer-string-raw",
      "unicorn/prefer-string-replace-all",
      "unicorn/prefer-string-slice",
      "unicorn/prefer-string-starts-ends-with",
      "unicorn/prefer-string-trim-start-end",
      "unicorn/prefer-structured-clone",
      "unicorn/prefer-switch",
      "unicorn/prefer-ternary",
      "unicorn/prefer-type-error",
      "unicorn/require-array-join-separator",
      "unicorn/require-number-to-fixed-digits-argument",
      "unicorn/require-post-message-target-origin",
      "unicorn/throw-new-error",
    ],
  },
  {
    "files": [
      "**/*.?([cm])ts?(x)",
    ],
    "ignores": [
      "**/*.md/**",
    ],
    "languageOptions": {
      "parser": "typescript-eslint/parser",
      "parserOptions": {
        "sourceType": "module",
      },
    },
    "name": "fabdeh/app/typescript/setup",
  },
  {
    "files": [
      "**/*.?([cm])ts?(x)",
    ],
    "ignores": [
      "**/*.md/**",
    ],
    "name": "fabdeh/app/typescript/rules",
    "plugins": [
      "@typescript-eslint",
      "unused-imports",
    ],
    "rules": [
      "- constructor-super",
      "- getter-return",
      "- no-class-assign",
      "- no-const-assign",
      "- no-dupe-args",
      "- no-dupe-class-members",
      "- no-dupe-keys",
      "- no-func-assign",
      "- no-import-assign",
      "- no-new-native-nonconstructor",
      "- no-new-symbol",
      "- no-obj-calls",
      "- no-redeclare",
      "- no-setter-return",
      "- no-this-before-super",
      "- no-undef",
      "- no-unreachable",
      "- no-unsafe-negation",
      "no-var",
      "- no-with",
      "prefer-const",
      "prefer-rest-params",
      "prefer-spread",
      "@typescript-eslint/await-thenable",
      "@typescript-eslint/ban-ts-comment",
      "- no-array-constructor",
      "@typescript-eslint/no-array-constructor",
      "@typescript-eslint/no-array-delete",
      "@typescript-eslint/no-base-to-string",
      "@typescript-eslint/no-confusing-void-expression",
      "@typescript-eslint/no-deprecated",
      "@typescript-eslint/no-duplicate-enum-values",
      "@typescript-eslint/no-duplicate-type-constituents",
      "@typescript-eslint/no-dynamic-delete",
      "@typescript-eslint/no-empty-object-type",
      "@typescript-eslint/no-explicit-any",
      "@typescript-eslint/no-extra-non-null-assertion",
      "@typescript-eslint/no-extraneous-class",
      "@typescript-eslint/no-floating-promises",
      "@typescript-eslint/no-for-in-array",
      "- no-implied-eval",
      "@typescript-eslint/no-implied-eval",
      "@typescript-eslint/no-invalid-void-type",
      "@typescript-eslint/no-meaningless-void-operator",
      "@typescript-eslint/no-misused-new",
      "@typescript-eslint/no-misused-promises",
      "@typescript-eslint/no-misused-spread",
      "@typescript-eslint/no-mixed-enums",
      "@typescript-eslint/no-namespace",
      "@typescript-eslint/no-non-null-asserted-nullish-coalescing",
      "@typescript-eslint/no-non-null-asserted-optional-chain",
      "@typescript-eslint/no-non-null-assertion",
      "@typescript-eslint/no-redundant-type-constituents",
      "@typescript-eslint/no-require-imports",
      "@typescript-eslint/no-this-alias",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare",
      "@typescript-eslint/no-unnecessary-condition",
      "@typescript-eslint/no-unnecessary-template-expression",
      "@typescript-eslint/no-unnecessary-type-arguments",
      "@typescript-eslint/no-unnecessary-type-assertion",
      "@typescript-eslint/no-unnecessary-type-constraint",
      "@typescript-eslint/no-unnecessary-type-conversion",
      "@typescript-eslint/no-unnecessary-type-parameters",
      "@typescript-eslint/no-unsafe-argument",
      "@typescript-eslint/no-unsafe-assignment",
      "@typescript-eslint/no-unsafe-call",
      "@typescript-eslint/no-unsafe-declaration-merging",
      "@typescript-eslint/no-unsafe-enum-comparison",
      "@typescript-eslint/no-unsafe-function-type",
      "@typescript-eslint/no-unsafe-member-access",
      "@typescript-eslint/no-unsafe-return",
      "@typescript-eslint/no-unsafe-unary-minus",
      "- no-unused-expressions",
      "@typescript-eslint/no-unused-expressions",
      "- no-unused-vars",
      "- @typescript-eslint/no-unused-vars",
      "- no-useless-constructor",
      "@typescript-eslint/no-useless-constructor",
      "@typescript-eslint/no-useless-default-assignment",
      "@typescript-eslint/no-wrapper-object-types",
      "- no-throw-literal",
      "@typescript-eslint/only-throw-error",
      "@typescript-eslint/prefer-as-const",
      "@typescript-eslint/prefer-literal-enum-member",
      "@typescript-eslint/prefer-namespace-keyword",
      "- prefer-promise-reject-errors",
      "@typescript-eslint/prefer-promise-reject-errors",
      "@typescript-eslint/prefer-reduce-type-parameter",
      "@typescript-eslint/prefer-return-this-type",
      "@typescript-eslint/related-getter-setter-pairs",
      "- require-await",
      "@typescript-eslint/require-await",
      "@typescript-eslint/restrict-plus-operands",
      "- @typescript-eslint/restrict-template-expressions",
      "- no-return-await",
      "@typescript-eslint/return-await",
      "@typescript-eslint/triple-slash-reference",
      "@typescript-eslint/unbound-method",
      "@typescript-eslint/unified-signatures",
      "@typescript-eslint/use-unknown-in-catch-callback-variable",
      "@typescript-eslint/adjacent-overload-signatures",
      "@typescript-eslint/array-type",
      "@typescript-eslint/ban-tslint-comment",
      "@typescript-eslint/class-literal-property-style",
      "@typescript-eslint/consistent-generic-constructors",
      "@typescript-eslint/consistent-indexed-object-style",
      "@typescript-eslint/consistent-type-assertions",
      "@typescript-eslint/consistent-type-definitions",
      "- dot-notation",
      "@typescript-eslint/dot-notation",
      "@typescript-eslint/no-confusing-non-null-assertion",
      "- no-empty-function",
      "@typescript-eslint/no-empty-function",
      "@typescript-eslint/no-inferrable-types",
      "@typescript-eslint/non-nullable-type-assertion-style",
      "@typescript-eslint/prefer-find",
      "@typescript-eslint/prefer-for-of",
      "@typescript-eslint/prefer-function-type",
      "@typescript-eslint/prefer-includes",
      "@typescript-eslint/prefer-nullish-coalescing",
      "@typescript-eslint/prefer-optional-chain",
      "@typescript-eslint/prefer-regexp-exec",
      "@typescript-eslint/prefer-string-starts-ends-with",
      "@typescript-eslint/consistent-type-exports",
      "@typescript-eslint/consistent-type-imports",
      "@typescript-eslint/explicit-member-accessibility",
      "@typescript-eslint/explicit-module-boundary-types",
      "@typescript-eslint/member-ordering",
      "@typescript-eslint/method-signature-style",
      "@typescript-eslint/naming-convention",
      "- @typescript-eslint/no-empty-interface",
      "@typescript-eslint/parameter-properties",
      "@typescript-eslint/prefer-enum-initializers",
      "@typescript-eslint/prefer-readonly",
      "@typescript-eslint/require-array-sort-compare",
      "@typescript-eslint/switch-exhaustiveness-check",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/stylistic/rules",
    "plugins": [
      "@stylistic",
    ],
    "rules": [
      "@stylistic/array-bracket-spacing",
      "@stylistic/arrow-parens",
      "@stylistic/arrow-spacing",
      "@stylistic/block-spacing",
      "@stylistic/brace-style",
      "@stylistic/comma-dangle",
      "@stylistic/comma-spacing",
      "@stylistic/comma-style",
      "@stylistic/computed-property-spacing",
      "@stylistic/dot-location",
      "@stylistic/eol-last",
      "@stylistic/generator-star-spacing",
      "@stylistic/indent",
      "@stylistic/indent-binary-ops",
      "@stylistic/key-spacing",
      "@stylistic/keyword-spacing",
      "@stylistic/lines-between-class-members",
      "@stylistic/max-statements-per-line",
      "@stylistic/member-delimiter-style",
      "@stylistic/multiline-ternary",
      "@stylistic/new-parens",
      "@stylistic/no-extra-parens",
      "@stylistic/no-floating-decimal",
      "@stylistic/no-mixed-operators",
      "@stylistic/no-mixed-spaces-and-tabs",
      "@stylistic/no-multi-spaces",
      "@stylistic/no-multiple-empty-lines",
      "@stylistic/no-tabs",
      "@stylistic/no-trailing-spaces",
      "@stylistic/no-whitespace-before-property",
      "@stylistic/object-curly-spacing",
      "@stylistic/operator-linebreak",
      "@stylistic/padded-blocks",
      "@stylistic/quote-props",
      "@stylistic/quotes",
      "@stylistic/rest-spread-spacing",
      "@stylistic/semi",
      "@stylistic/semi-spacing",
      "@stylistic/space-before-blocks",
      "@stylistic/space-before-function-paren",
      "@stylistic/space-in-parens",
      "@stylistic/space-infix-ops",
      "@stylistic/space-unary-ops",
      "@stylistic/spaced-comment",
      "@stylistic/template-curly-spacing",
      "@stylistic/template-tag-spacing",
      "@stylistic/type-annotation-spacing",
      "@stylistic/type-generic-spacing",
      "@stylistic/type-named-tuple-spacing",
      "@stylistic/wrap-iife",
      "@stylistic/yield-star-spacing",
      "@stylistic/jsx-closing-bracket-location",
      "@stylistic/jsx-closing-tag-location",
      "@stylistic/jsx-curly-brace-presence",
      "@stylistic/jsx-curly-newline",
      "@stylistic/jsx-curly-spacing",
      "@stylistic/jsx-equals-spacing",
      "@stylistic/jsx-first-prop-new-line",
      "@stylistic/jsx-function-call-newline",
      "@stylistic/jsx-indent-props",
      "@stylistic/jsx-max-props-per-line",
      "@stylistic/jsx-one-expression-per-line",
      "@stylistic/jsx-quotes",
      "@stylistic/jsx-tag-spacing",
      "@stylistic/jsx-wrap-multilines",
      "@stylistic/no-extra-semi",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/regexp/rules",
    "plugins": [
      "regexp",
    ],
    "rules": [
      "no-control-regex",
      "no-misleading-character-class",
      "no-regex-spaces",
      "prefer-regex-literals",
      "- no-invalid-regexp",
      "- no-useless-backreference",
      "- no-empty-character-class",
      "regexp/confusing-quantifier",
      "regexp/control-character-escape",
      "regexp/match-any",
      "regexp/negation",
      "regexp/no-contradiction-with-assertion",
      "regexp/no-dupe-characters-character-class",
      "regexp/no-dupe-disjunctions",
      "regexp/no-empty-alternative",
      "regexp/no-empty-capturing-group",
      "regexp/no-empty-character-class",
      "regexp/no-empty-group",
      "regexp/no-empty-lookarounds-assertion",
      "regexp/no-empty-string-literal",
      "regexp/no-escape-backspace",
      "regexp/no-extra-lookaround-assertions",
      "regexp/no-invalid-regexp",
      "regexp/no-invisible-character",
      "regexp/no-lazy-ends",
      "regexp/no-legacy-features",
      "regexp/no-misleading-capturing-group",
      "regexp/no-misleading-unicode-character",
      "regexp/no-missing-g-flag",
      "regexp/no-non-standard-flag",
      "regexp/no-obscure-range",
      "regexp/no-optional-assertion",
      "regexp/no-potentially-useless-backreference",
      "regexp/no-super-linear-backtracking",
      "regexp/no-trivially-nested-assertion",
      "regexp/no-trivially-nested-quantifier",
      "regexp/no-unused-capturing-group",
      "regexp/no-useless-assertions",
      "regexp/no-useless-backreference",
      "regexp/no-useless-character-class",
      "regexp/no-useless-dollar-replacements",
      "regexp/no-useless-escape",
      "regexp/no-useless-flag",
      "regexp/no-useless-lazy",
      "regexp/no-useless-non-capturing-group",
      "regexp/no-useless-quantifier",
      "regexp/no-useless-range",
      "regexp/no-useless-set-operand",
      "regexp/no-useless-string-literal",
      "regexp/no-useless-two-nums-quantifier",
      "regexp/no-zero-quantifier",
      "regexp/optimal-lookaround-quantifier",
      "regexp/optimal-quantifier-concatenation",
      "regexp/prefer-character-class",
      "regexp/prefer-d",
      "regexp/prefer-plus-quantifier",
      "regexp/prefer-predefined-assertion",
      "regexp/prefer-question-quantifier",
      "regexp/prefer-range",
      "regexp/prefer-set-operation",
      "regexp/prefer-star-quantifier",
      "regexp/prefer-unicode-codepoint-escapes",
      "regexp/prefer-w",
      "regexp/simplify-set-operations",
      "regexp/sort-flags",
      "regexp/strict",
      "regexp/use-ignore-case",
    ],
  },
  {
    "files": [
      "**/*.?([cm])ts?(x)",
    ],
    "name": "fabdeh/angular/rules",
    "plugins": [
      "@angular-eslint",
    ],
    "processor": "extract-inline-html",
    "rules": [
      "max-classes-per-file",
      "max-lines",
      "new-cap",
      "@angular-eslint/contextual-lifecycle",
      "@angular-eslint/no-empty-lifecycle-method",
      "@angular-eslint/no-input-rename",
      "@angular-eslint/no-inputs-metadata-property",
      "@angular-eslint/no-output-native",
      "@angular-eslint/no-output-on-prefix",
      "@angular-eslint/no-output-rename",
      "@angular-eslint/no-outputs-metadata-property",
      "@angular-eslint/prefer-inject",
      "@angular-eslint/prefer-standalone",
      "@angular-eslint/use-pipe-transform-interface",
      "@angular-eslint/use-lifecycle-interface",
      "@angular-eslint/component-max-inline-declarations",
      "@angular-eslint/component-selector",
      "@angular-eslint/consistent-component-styles",
      "@angular-eslint/contextual-decorator",
      "@angular-eslint/directive-selector",
      "@angular-eslint/no-async-lifecycle-method",
      "@angular-eslint/no-attribute-decorator",
      "@angular-eslint/no-developer-preview",
      "@angular-eslint/no-duplicates-in-metadata-arrays",
      "@angular-eslint/no-experimental",
      "@angular-eslint/no-forward-ref",
      "@angular-eslint/no-lifecycle-call",
      "@angular-eslint/no-pipe-impure",
      "@angular-eslint/no-queries-metadata-property",
      "@angular-eslint/no-uncalled-signals",
      "@angular-eslint/prefer-output-emitter-ref",
      "@angular-eslint/prefer-output-readonly",
      "@angular-eslint/prefer-signals",
      "@angular-eslint/prefer-on-push-component-change-detection",
      "@angular-eslint/relative-url-prefix",
      "@angular-eslint/require-lifecycle-on-prototype",
      "@angular-eslint/sort-keys-in-type-decorator",
      "@angular-eslint/sort-lifecycle-methods",
      "@angular-eslint/use-component-selector",
      "@angular-eslint/use-component-view-encapsulation",
      "@angular-eslint/use-injectable-provided-in",
    ],
  },
  {
    "files": [
      "**/*.htm?(l)",
    ],
    "languageOptions": {
      "parser": "angular-eslint/template-parser",
    },
    "name": "fabdeh/angular-template/rules",
    "plugins": [
      "@angular-eslint/template",
    ],
    "rules": [
      "@angular-eslint/template/banana-in-box",
      "@angular-eslint/template/eqeqeq",
      "@angular-eslint/template/no-negated-async",
      "@angular-eslint/template/prefer-control-flow",
      "@angular-eslint/template/attributes-order",
      "@angular-eslint/template/button-has-type",
      "@angular-eslint/template/conditional-complexity",
      "@angular-eslint/template/no-any",
      "@angular-eslint/template/no-duplicate-attributes",
      "@angular-eslint/template/no-interpolation-in-attributes",
      "@angular-eslint/template/no-positive-tabindex",
      "@angular-eslint/template/prefer-ngsrc",
      "@angular-eslint/template/prefer-self-closing-tags",
      "@angular-eslint/template/prefer-static-string-properties",
      "@angular-eslint/template/alt-text",
      "@angular-eslint/template/click-events-have-key-events",
      "@angular-eslint/template/elements-content",
      "@angular-eslint/template/interactive-supports-focus",
      "@angular-eslint/template/label-has-associated-control",
      "@angular-eslint/template/mouse-events-have-key-events",
      "@angular-eslint/template/no-autofocus",
      "@angular-eslint/template/no-distracting-elements",
      "@angular-eslint/template/role-has-required-aria",
      "@angular-eslint/template/table-scope",
      "@angular-eslint/template/valid-aria",
    ],
  },
  {
    "files": [
      [
        "**/*.actions.?([cm])ts?(x)",
        "**/*.feature.?([cm])ts?(x)",
        "**/*.reducer.?([cm])ts?(x)",
        "**/*.state.?([cm])ts?(x)",
      ],
      [
        "**/*.effects.?([cm])ts?(x)",
      ],
      [
        "**/*.store.?([cm])ts?(x)",
      ],
    ],
    "name": "fabdeh/ngrx/setup",
    "plugins": [
      "@ngrx",
    ],
  },
  {
    "files": [
      "**/*.actions.?([cm])ts?(x)",
      "**/*.feature.?([cm])ts?(x)",
      "**/*.reducer.?([cm])ts?(x)",
      "**/*.state.?([cm])ts?(x)",
    ],
    "name": "fabdeh/ngrx-store/rules",
    "rules": [
      "@ngrx/avoid-combining-selectors",
      "@ngrx/avoid-dispatching-multiple-actions-sequentially",
      "@ngrx/avoid-duplicate-actions-in-reducer",
      "@ngrx/avoid-mapping-selectors",
      "@ngrx/good-action-hygiene",
      "@ngrx/no-multiple-global-stores",
      "@ngrx/no-reducer-in-key-names",
      "@ngrx/no-store-subscription",
      "@ngrx/no-typed-global-store",
      "@ngrx/on-function-explicit-return-type",
      "@ngrx/prefer-action-creator-in-dispatch",
      "@ngrx/prefer-action-creator",
      "@ngrx/prefer-inline-action-props",
      "@ngrx/prefer-one-generic-in-create-for-feature-selector",
      "@ngrx/prefer-selector-in-select",
      "@ngrx/prefix-selectors-with-select",
      "@ngrx/select-style",
      "@ngrx/use-consistent-global-store-name",
      "@typescript-eslint/naming-convention",
    ],
  },
  {
    "files": [
      "**/*.effects.?([cm])ts?(x)",
    ],
    "name": "fabdeh/ngrx-effects/rules",
    "rules": [
      "@ngrx/no-dispatch-in-effects",
      "@ngrx/no-effects-in-providers",
      "@ngrx/prefer-action-creator-in-of-type",
      "@ngrx/prefer-effect-callback-in-block-statement",
      "@ngrx/use-effects-lifecycle-interface",
      "@typescript-eslint/naming-convention",
    ],
  },
  {
    "files": [
      "**/*.store.?([cm])ts?(x)",
    ],
    "name": "fabdeh/ngrx-signals/rules",
    "rules": [
      "@ngrx/enforce-type-call",
      "@ngrx/prefer-protected-state",
      "@ngrx/signal-store-feature-should-use-generic-type",
      "@typescript-eslint/naming-convention",
    ],
  },
  {
    "files": [
      [
        "**/*.actions.?([cm])ts?(x)",
        "**/*.feature.?([cm])ts?(x)",
        "**/*.reducer.?([cm])ts?(x)",
        "**/*.state.?([cm])ts?(x)",
      ],
      [
        "**/*.effects.?([cm])ts?(x)",
      ],
      [
        "**/*.store.?([cm])ts?(x)",
      ],
    ],
    "name": "fabdeh/ngrx-operators/rules",
    "rules": [
      "@ngrx/prefer-concat-latest-from",
    ],
  },
  {
    "files": [
      "**/*.spec.?([cm])[jt]s",
      "**/*.test.?([cm])[jt]s",
      "**/test-setup.?([cm])[jt]s",
    ],
    "ignores": [
      "e2e",
    ],
    "languageOptions": {},
    "name": "fabdeh/vitest/rules",
    "plugins": [
      "vitest",
      "jest-dom",
      "testing-library",
    ],
    "rules": [
      "vitest/expect-expect",
      "vitest/no-commented-out-tests",
      "vitest/no-conditional-expect",
      "vitest/no-disabled-tests",
      "vitest/no-focused-tests",
      "vitest/no-identical-title",
      "vitest/no-import-node-test",
      "vitest/no-interpolation-in-snapshots",
      "vitest/no-mocks-import",
      "vitest/no-standalone-expect",
      "vitest/no-unneeded-async-expect-function",
      "- vitest/prefer-called-exactly-once-with",
      "vitest/require-local-test-context-for-concurrent-snapshots",
      "vitest/valid-describe-callback",
      "vitest/valid-expect",
      "vitest/valid-expect-in-promise",
      "vitest/valid-title",
      "jest-dom/prefer-checked",
      "jest-dom/prefer-empty",
      "jest-dom/prefer-enabled-disabled",
      "jest-dom/prefer-focus",
      "jest-dom/prefer-in-document",
      "jest-dom/prefer-required",
      "jest-dom/prefer-to-have-attribute",
      "jest-dom/prefer-to-have-class",
      "jest-dom/prefer-to-have-style",
      "jest-dom/prefer-to-have-text-content",
      "jest-dom/prefer-to-have-value",
      "testing-library/await-async-events",
      "testing-library/await-async-queries",
      "testing-library/await-async-utils",
      "testing-library/no-await-sync-events",
      "testing-library/no-await-sync-queries",
      "testing-library/no-container",
      "testing-library/no-debugging-utils",
      "testing-library/no-dom-import",
      "testing-library/no-global-regexp-flag-in-query",
      "testing-library/no-node-access",
      "testing-library/no-promise-in-fire-event",
      "testing-library/no-render-in-lifecycle",
      "testing-library/no-wait-for-multiple-assertions",
      "testing-library/no-wait-for-side-effects",
      "testing-library/no-wait-for-snapshot",
      "testing-library/prefer-find-by",
      "testing-library/prefer-presence-queries",
      "testing-library/prefer-query-by-disappearance",
      "testing-library/prefer-screen-queries",
      "testing-library/render-result-naming-convention",
      "- max-classes-per-file",
      "- max-lines",
      "- @typescript-eslint/consistent-type-assertions",
      "- @typescript-eslint/no-empty-function",
      "- @typescript-eslint/no-unsafe-assignment",
      "- @typescript-eslint/no-unsafe-call",
      "- @typescript-eslint/no-unsafe-member-access",
      "- @typescript-eslint/unbound-method",
      "- unicorn/no-null",
      "vitest/consistent-test-it",
      "vitest/no-test-return-statement",
      "vitest/prefer-hooks-in-order",
      "vitest/prefer-hooks-on-top",
      "vitest/prefer-lowercase-title",
      "vitest/prefer-spy-on",
      "vitest/prefer-to-be",
      "vitest/prefer-to-be-falsy",
      "vitest/prefer-to-be-object",
      "vitest/prefer-to-be-truthy",
      "vitest/prefer-to-contain",
      "vitest/prefer-to-have-length",
      "vitest/prefer-todo",
      "vitest/prefer-vi-mocked",
      "vitest/require-top-level-describe",
      "- jsdoc/check-access",
      "- jsdoc/check-param-names",
      "- jsdoc/check-property-names",
      "jsdoc/check-tag-names",
      "- jsdoc/check-types",
      "- jsdoc/check-values",
      "- jsdoc/empty-tags",
      "- jsdoc/implements-on-classes",
      "- jsdoc/no-defaults",
      "- jsdoc/no-undefined-types",
      "- jsdoc/require-jsdoc",
      "- jsdoc/require-param",
      "- jsdoc/require-param-description",
      "- jsdoc/require-param-name",
      "- jsdoc/require-param-type",
      "- jsdoc/require-property",
      "- jsdoc/require-property-description",
      "- jsdoc/require-property-name",
      "- jsdoc/require-property-type",
      "- jsdoc/require-returns",
      "- jsdoc/require-returns-check",
      "- jsdoc/require-returns-description",
      "- jsdoc/require-returns-type",
      "- jsdoc/require-yields",
      "- jsdoc/require-yields-check",
      "- jsdoc/valid-types",
      "- jsdoc/check-alignment",
      "- jsdoc/multiline-blocks",
      "- jsdoc/no-multi-asterisks",
      "- jsdoc/require-asterisk-prefix",
      "- jsdoc/require-hyphen-before-param-description",
      "jsdoc/tag-lines",
      "- jsdoc/no-types",
    ],
    "settings": {
      "vitest": {
        "typecheck": true,
      },
    },
  },
  {
    "name": "fabdeh/jsonc/setup",
    "plugins": [
      "jsonc",
    ],
  },
  {
    "files": [
      "**/*.json",
      "**/*.json5",
      "**/*.jsonc",
    ],
    "languageOptions": {
      "parser": "jsonc-eslint-parser",
    },
    "name": "fabdeh/jsonc/rules",
    "rules": [
      "jsonc/no-bigint-literals",
      "jsonc/no-binary-expression",
      "jsonc/no-binary-numeric-literals",
      "jsonc/no-dupe-keys",
      "jsonc/no-escape-sequence-in-identifier",
      "jsonc/no-floating-decimal",
      "jsonc/no-hexadecimal-numeric-literals",
      "jsonc/no-infinity",
      "jsonc/no-multi-str",
      "jsonc/no-nan",
      "jsonc/no-number-props",
      "jsonc/no-numeric-separators",
      "jsonc/no-octal",
      "jsonc/no-octal-escape",
      "jsonc/no-octal-numeric-literals",
      "jsonc/no-parenthesized",
      "jsonc/no-plus-sign",
      "jsonc/no-regexp-literals",
      "jsonc/no-sparse-arrays",
      "jsonc/no-template-literals",
      "jsonc/no-undefined-value",
      "jsonc/no-unicode-codepoint-escapes",
      "jsonc/no-useless-escape",
      "jsonc/space-unary-ops",
      "jsonc/valid-json-number",
      "jsonc/vue-custom-block/no-parsing-error",
      "jsonc/array-bracket-spacing",
      "jsonc/comma-dangle",
      "jsonc/comma-style",
      "jsonc/indent",
      "jsonc/key-spacing",
      "jsonc/object-curly-newline",
      "jsonc/object-curly-spacing",
      "jsonc/object-property-newline",
      "jsonc/quote-props",
      "jsonc/quotes",
    ],
  },
  {
    "files": [
      "**/package.json",
    ],
    "name": "fabdeh/sort/package-json",
    "rules": [
      "jsonc/sort-array-values",
      "jsonc/sort-keys",
    ],
  },
  {
    "files": [
      "**/tsconfig.json",
      "**/tsconfig.*.json",
    ],
    "name": "fabdeh/sort/tsconfig-json",
    "rules": [
      "jsonc/sort-keys",
    ],
  },
  {
    "name": "fabdeh/yaml/setup",
    "plugins": [
      "yaml",
    ],
  },
  {
    "files": [
      "**/*.y?(a)ml",
    ],
    "language": "yaml/yaml",
    "name": "fabdeh/yaml/rules",
    "rules": [
      "- @stylistic/spaced-comment",
      "yaml/block-mapping",
      "yaml/block-sequence",
      "yaml/no-empty-key",
      "yaml/no-empty-sequence-entry",
      "yaml/no-irregular-whitespace",
      "yaml/plain-scalar",
      "yaml/vue-custom-block/no-parsing-error",
      "yaml/block-mapping-question-indicator-newline",
      "yaml/block-sequence-hyphen-indicator-newline",
      "yaml/flow-mapping-curly-newline",
      "yaml/flow-mapping-curly-spacing",
      "yaml/flow-sequence-bracket-newline",
      "yaml/flow-sequence-bracket-spacing",
      "yaml/indent",
      "yaml/key-spacing",
      "yaml/no-tab-indent",
      "yaml/quotes",
      "yaml/spaced-comment",
    ],
  },
  {
    "name": "fabdeh/toml/setup",
    "plugins": [
      "toml",
    ],
  },
  {
    "files": [
      "**/*.toml",
    ],
    "language": "toml/toml",
    "name": "fabdeh/toml/rules",
    "rules": [
      "- @stylistic/spaced-comment",
      "toml/comma-style",
      "toml/keys-order",
      "toml/no-space-dots",
      "toml/no-unreadable-number-separator",
      "toml/precision-of-fractional-seconds",
      "toml/precision-of-integer",
      "toml/tables-order",
      "toml/vue-custom-block/no-parsing-error",
      "toml/array-bracket-newline",
      "toml/array-bracket-spacing",
      "toml/array-element-newline",
      "toml/indent",
      "toml/inline-table-curly-spacing",
      "toml/key-spacing",
      "toml/padding-line-between-pairs",
      "toml/padding-line-between-tables",
      "toml/quoted-keys",
      "toml/spaced-comment",
      "toml/table-bracket-spacing",
    ],
  },
  {
    "name": "fabdeh/markdown/setup",
    "plugins": [
      "markdown",
    ],
  },
  {
    "files": [
      "**/*.md",
    ],
    "ignores": [
      "**/*.md/*.md",
    ],
    "name": "fabdeh/markdown/processor",
    "processor": "merged-processor:@eslint/markdown/markdown+pass-through",
  },
  {
    "files": [
      "**/*.md",
    ],
    "languageOptions": {
      "parser": "parser-plain",
    },
    "name": "fabdeh/markdown/parser",
  },
  {
    "files": [
      "**/*.md/**/*.?([cm])[jt]s?(x)",
    ],
    "languageOptions": {
      "parserOptions": {
        "ecmaFeatures": {
          "impliedStrict": true,
        },
      },
    },
    "name": "fabdeh/markdown/disables",
    "rules": [
      "- @typescript-eslint/await-thenable",
      "- @typescript-eslint/consistent-return",
      "- @typescript-eslint/consistent-type-exports",
      "- @typescript-eslint/dot-notation",
      "- @typescript-eslint/naming-convention",
      "- @typescript-eslint/no-array-delete",
      "- @typescript-eslint/no-base-to-string",
      "- @typescript-eslint/no-confusing-void-expression",
      "- @typescript-eslint/no-deprecated",
      "- @typescript-eslint/no-duplicate-type-constituents",
      "- @typescript-eslint/no-floating-promises",
      "- @typescript-eslint/no-for-in-array",
      "- @typescript-eslint/no-implied-eval",
      "- @typescript-eslint/no-meaningless-void-operator",
      "- @typescript-eslint/no-misused-promises",
      "- @typescript-eslint/no-misused-spread",
      "- @typescript-eslint/no-mixed-enums",
      "- @typescript-eslint/no-redundant-type-constituents",
      "- @typescript-eslint/no-unnecessary-boolean-literal-compare",
      "- @typescript-eslint/no-unnecessary-condition",
      "- @typescript-eslint/no-unnecessary-qualifier",
      "- @typescript-eslint/no-unnecessary-template-expression",
      "- @typescript-eslint/no-unnecessary-type-arguments",
      "- @typescript-eslint/no-unnecessary-type-assertion",
      "- @typescript-eslint/no-unnecessary-type-conversion",
      "- @typescript-eslint/no-unnecessary-type-parameters",
      "- @typescript-eslint/no-unsafe-argument",
      "- @typescript-eslint/no-unsafe-assignment",
      "- @typescript-eslint/no-unsafe-call",
      "- @typescript-eslint/no-unsafe-enum-comparison",
      "- @typescript-eslint/no-unsafe-member-access",
      "- @typescript-eslint/no-unsafe-return",
      "- @typescript-eslint/no-unsafe-type-assertion",
      "- @typescript-eslint/no-unsafe-unary-minus",
      "- @typescript-eslint/no-useless-default-assignment",
      "- @typescript-eslint/non-nullable-type-assertion-style",
      "- @typescript-eslint/only-throw-error",
      "- @typescript-eslint/prefer-destructuring",
      "- @typescript-eslint/prefer-find",
      "- @typescript-eslint/prefer-includes",
      "- @typescript-eslint/prefer-nullish-coalescing",
      "- @typescript-eslint/prefer-optional-chain",
      "- @typescript-eslint/prefer-promise-reject-errors",
      "- @typescript-eslint/prefer-readonly",
      "- @typescript-eslint/prefer-readonly-parameter-types",
      "- @typescript-eslint/prefer-reduce-type-parameter",
      "- @typescript-eslint/prefer-regexp-exec",
      "- @typescript-eslint/prefer-return-this-type",
      "- @typescript-eslint/prefer-string-starts-ends-with",
      "- @typescript-eslint/promise-function-async",
      "- @typescript-eslint/related-getter-setter-pairs",
      "- @typescript-eslint/require-array-sort-compare",
      "- @typescript-eslint/require-await",
      "- @typescript-eslint/restrict-plus-operands",
      "- @typescript-eslint/restrict-template-expressions",
      "- @typescript-eslint/return-await",
      "- @typescript-eslint/strict-boolean-expressions",
      "- @typescript-eslint/strict-void-return",
      "- @typescript-eslint/switch-exhaustiveness-check",
      "- @typescript-eslint/unbound-method",
      "- @typescript-eslint/use-unknown-in-catch-callback-variable",
      "- import-x/newline-after-import",
      "- no-alert",
      "- no-console",
      "- no-labels",
      "- no-lone-blocks",
      "- no-restricted-syntax",
      "- no-undef",
      "- no-unused-expressions",
      "- no-unused-labels",
      "- no-unused-vars",
      "- @stylistic/comma-dangle",
      "- @stylistic/eol-last",
      "- @typescript-eslint/consistent-type-imports",
      "- @typescript-eslint/explicit-function-return-type",
      "- @typescript-eslint/no-namespace",
      "- @typescript-eslint/no-redeclare",
      "- @typescript-eslint/no-require-imports",
      "- @typescript-eslint/no-unused-expressions",
      "- @typescript-eslint/no-unused-vars",
      "- @typescript-eslint/no-use-before-define",
      "- unicode-bom",
      "- unused-imports/no-unused-imports",
      "- unused-imports/no-unused-vars",
    ],
  },
  {
    "files": [
      "**/*.md",
    ],
    "name": "fabdeh/markdown/rules",
    "rules": [
      "markdown/fenced-code-language",
      "markdown/heading-increment",
      "markdown/no-duplicate-definitions",
      "markdown/no-empty-definitions",
      "markdown/no-empty-images",
      "markdown/no-empty-links",
      "markdown/no-invalid-label-refs",
      "markdown/no-missing-atx-heading-space",
      "markdown/no-missing-label-refs",
      "markdown/no-missing-link-fragments",
      "markdown/no-multiple-h1",
      "markdown/no-reference-like-urls",
      "markdown/no-reversed-media-syntax",
      "markdown/no-space-in-emphasis",
      "markdown/no-unused-definitions",
      "markdown/require-alt-text",
      "markdown/table-column-count",
      "markdown/no-duplicate-headings",
    ],
  },
]