[
  "<ignored>",
  "<ignored>",
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/javascript/rules",
    "plugins": [
      "@typescript-eslint",
      "prefer-arrow-functions",
      "unused-imports",
    ],
    "rules": [
      "accessor-pairs",
      "array-callback-return",
      "block-scoped-var",
      "constructor-super",
      "default-case-last",
      "dot-notation",
      "eqeqeq",
      "for-direction",
      "getter-return",
      "id-denylist",
      "new-cap",
      "no-alert",
      "no-async-promise-executor",
      "no-caller",
      "no-case-declarations",
      "no-class-assign",
      "no-cond-assign",
      "no-compare-neg-zero",
      "no-console",
      "no-const-assign",
      "no-constant-binary-expression",
      "no-constant-condition",
      "no-control-regex",
      "no-debugger",
      "no-delete-var",
      "no-dupe-args",
      "no-dupe-class-members",
      "no-dupe-else-if",
      "no-dupe-keys",
      "no-duplicate-case",
      "no-empty",
      "no-empty-character-class",
      "no-empty-pattern",
      "no-empty-static-block",
      "no-eval",
      "no-ex-assign",
      "no-extend-native",
      "no-extra-bind",
      "no-extra-boolean-cast",
      "no-fallthrough",
      "no-func-assign",
      "no-global-assign",
      "no-import-assign",
      "no-implied-eval",
      "no-invalid-regexp",
      "no-irregular-whitespace",
      "no-iterator",
      "no-labels",
      "no-lone-blocks",
      "no-lonely-if",
      "no-loss-of-precision",
      "no-misleading-character-class",
      "no-multi-str",
      "no-new",
      "no-new-func",
      "no-new-native-nonconstructor",
      "no-new-wrappers",
      "no-nonoctal-decimal-escape",
      "no-obj-calls",
      "no-octal",
      "no-octal-escape",
      "no-plusplus",
      "no-prototype-builtins",
      "no-proto",
      "no-redeclare",
      "no-regex-spaces",
      "no-restricted-globals",
      "no-restricted-properties",
      "no-restricted-syntax",
      "no-self-assign",
      "no-self-compare",
      "no-sequences",
      "no-setter-return",
      "no-shadow-restricted-names",
      "no-sparse-arrays",
      "no-template-curly-in-string",
      "no-this-before-super",
      "no-throw-literal",
      "no-undef",
      "no-undef-init",
      "no-unassigned-vars",
      "no-unexpected-multiline",
      "no-unmodified-loop-condition",
      "no-unneeded-ternary",
      "no-unreachable",
      "no-unreachable-loop",
      "no-unsafe-finally",
      "no-unsafe-negation",
      "no-unsafe-optional-chaining",
      "no-unused-expressions",
      "no-unused-labels",
      "no-unused-private-class-members",
      "- no-unused-vars",
      "no-use-before-define",
      "no-useless-assignment",
      "no-useless-backreference",
      "no-useless-call",
      "no-useless-catch",
      "no-useless-computed-key",
      "no-useless-constructor",
      "no-useless-escape",
      "no-useless-rename",
      "no-useless-return",
      "no-var",
      "no-with",
      "object-shorthand",
      "prefer-arrow-callback",
      "prefer-arrow-functions/prefer-arrow-functions",
      "prefer-const",
      "prefer-exponentiation-operator",
      "prefer-object-spread",
      "prefer-promise-reject-errors",
      "prefer-regex-literals",
      "prefer-rest-params",
      "prefer-spread",
      "prefer-template",
      "preserve-caught-error",
      "require-yield",
      "symbol-description",
      "unicode-bom",
      "use-isnan",
      "unused-imports/no-unused-imports",
      "unused-imports/no-unused-vars",
      "valid-typeof",
      "vars-on-top",
      "yoda",
      "@typescript-eslint/ban-ts-comment",
      "@typescript-eslint/no-extra-non-null-assertion",
      "@typescript-eslint/no-misused-new",
      "@typescript-eslint/no-non-null-asserted-optional-chain",
      "@typescript-eslint/no-require-imports",
      "@typescript-eslint/no-this-alias",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/comments/rules",
    "plugins": [
      "@eslint-community/eslint-comments",
    ],
    "rules": [
      "@eslint-community/eslint-comments/disable-enable-pair",
      "@eslint-community/eslint-comments/no-aggregating-enable",
      "@eslint-community/eslint-comments/no-duplicate-disable",
      "@eslint-community/eslint-comments/no-unlimited-disable",
      "@eslint-community/eslint-comments/no-unused-disable",
      "@eslint-community/eslint-comments/no-unused-enable",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/node/rules",
    "plugins": [
      "n",
    ],
    "rules": [
      "n/handle-callback-err",
      "n/no-callback-literal",
      "n/no-deprecated-api",
      "n/no-exports-assign",
      "n/no-new-require",
      "n/no-path-concat",
      "n/prefer-global/buffer",
      "n/prefer-global/process",
      "n/prefer-promises/dns",
      "n/prefer-promises/fs",
      "n/process-exit-as-throw",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/imports/rules",
    "plugins": [
      "import-x",
    ],
    "rules": [
      "import-x/consistent-type-specifier-style",
      "import-x/default",
      "import-x/export",
      "import-x/first",
      "import-x/named",
      "import-x/no-absolute-path",
      "import-x/no-deprecated",
      "import-x/no-duplicates",
      "import-x/no-empty-named-blocks",
      "import-x/no-extraneous-dependencies",
      "import-x/no-mutable-exports",
      "import-x/no-named-as-default",
      "import-x/no-named-as-default-member",
      "import-x/no-named-default",
      "import-x/no-self-import",
      "import-x/no-useless-path-segments",
      "import-x/no-webpack-loader-syntax",
    ],
  },
  {
    "files": [
      "**/*.?([cm])ts?(x)",
    ],
    "name": "fabdeh/imports/ts-disables",
    "rules": [
      "- import-x/named",
      "- import-x/no-deprecated",
    ],
  },
  {
    "files": [
      "**/*.?([cm])[jt]s?(x)",
    ],
    "name": "fabdeh/perfectionist/rules",
    "plugins": [
      "perfectionist",
    ],
    "rules": [
      "perfectionist/sort-exports",
      "perfectionist/sort-imports",
      "perfectionist/sort-intersection-types",
      "perfectionist/sort-named-exports",
      "perfectionist/sort-named-imports",
      "perfectionist/sort-switch-case",
      "perfectionist/sort-union-types",
    ],
  },
]