name: PR Title Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions: read-all

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Ensure's validate-pr-title.js is the copy from main
          ref: main
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Use latest corepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After: corepack version => $(corepack --version)"
          corepack enable
          pnpm --version
      - name: Install dependencies
        run: pnpm install
      - name: Validate PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
        run: pnpm validate-pr-title
