name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      dist-tag:
        description: NPM dist-tag
        required: true
        default: latest
        type: choice
        options:
          - latest
          - next

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - name: Use latest corepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After: corepack version => $(corepack --version)"
          corepack enable
          pnpm --version
      - name: Install dependencies
        run: pnpm install
      - if: github.event_name == 'workflow_dispatch'
        run: pnpm publish --tag $DIST_TAG
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DIST_TAG: ${{ inputs.dist-tag }}
      - if: github.event_name != 'workflow_dispatch'
        run: pnpm publish --tag latest
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
