name: Publish

on:
  workflow_run:
    workflows: [Release]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
          check-latest: true
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false # never uise caching in release publish
      - run: pnpm install
      - name: Get dist-tag
        id: get-version-tag
        run: |
          echo "dist-tag=$(node -p "require('semver/functions/prerelease')(require('./package.json').version) === null ? 'latest' : 'next'")" >> $GITHUB_OUTPUT
      - run: pnpm publish --tag $DIST_TAG
        env:
          NPM_CONFIG_PROVENANCE: true
          DIST_TAG: ${{ steps.get-version-tag.outputs.dist-tag }}
