name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  verify-tag-and-commit-signature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with tags
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Import GPG public key
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          KEY_ID: CE8F496F391D9711
          GH_USERNAME: FabienDehopre
        run: |
          gh api "/users/${GH_USERNAME}/gpg_keys" \
            --jq ".[] | select(.key_id == \"${KEY_ID}\") | .raw_key" \
            | gpg --import
      - name: Verify tag signature
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Verify tag: $TAG_NAME"
          git tag -v "$TAG_NAME"
      - name: Verify commit
        run: git verify-commit HEAD
  release:
    needs: verify-tag-and-commit-signature
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
