name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  verify-tag-and-commit-signature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Import GPG public key
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          KEY_ID: CE8F496F391D9711
          GH_USERNAME: FabienDehopre
        run: |
          gh api "/users/${GH_USERNAME}/gpg_keys" \
            --jq ".[] | select(.key_id == \"${KEY_ID}\") | .raw_key" \
            | gpg --import
      - name: Verify tag signature
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Verify tag: $TAG_NAME"
          git tag -v "$TAG_NAME"
      - name: Verify commit
        run: git verify-commit HEAD

  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
          check-latest: true
          cache: pnpm
      - run: pnpm install --frozen-lockfile --recursive
      - run: pnpm gen
      - run: pnpm typecheck
      - run: pnpm build:ci
      - run: pnpm lint:ci
      - run: pnpm check-exports
      - run: pnpm test

  release:
    needs: [verify-tag-and-commit-signature, check-code-quality]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: lts/*
      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
